language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
env:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
script: cd example && python manage.py test addendum
